#!/usr/bin/env python3
"""Build a minimal but valid TrueType font and emit it as an ABAP base64 class.

The font has three glyphs: .notdef, capital A and L with stroke (U+0141), the
second one on purpose outside WinAnsi. Advance widths are 600 and 500 units of
1000 per em, so the unit tests can assert exact text widths.
"""
import base64
import struct
import sys

UNITS = 1000
GLYPHS = [
    # (codepoint, advance width, box)
    (None, 500, None),
    (0x41, 600, (50, 0, 550, 700)),
    (0x141, 500, (50, 0, 450, 700)),
    (0x31, 400, (50, 0, 350, 700)),
    (0x32, 400, (50, 0, 350, 700)),
]


def simple_glyph(box):
    if box is None:
        return b""
    x0, y0, x1, y1 = box
    data = struct.pack(">hhhhh", 1, x0, y0, x1, y1)      # contours, bbox
    data += struct.pack(">H", 3)                          # endPtsOfContours
    data += struct.pack(">H", 0)                          # instructionLength
    data += bytes([0x01, 0x01, 0x01, 0x01])               # on curve, long deltas
    xs = [x0, x1 - x0, 0, -(x1 - x0)]
    ys = [y0, 0, y1 - y0, 0]
    data += b"".join(struct.pack(">h", v) for v in xs)
    data += b"".join(struct.pack(">h", v) for v in ys)
    if len(data) % 2:
        data += b"\0"
    return data


def cmap_format4():
    mapping = sorted((cp, gid) for gid, (cp, _, _) in enumerate(GLYPHS) if cp)
    segments = [(cp, cp, gid) for cp, gid in mapping] + [(0xFFFF, 0xFFFF, 0)]
    seg_count = len(segments)
    ends = b"".join(struct.pack(">H", s[1]) for s in segments)
    starts = b"".join(struct.pack(">H", s[0]) for s in segments)
    deltas = b"".join(struct.pack(">h", (s[2] - s[0]) if s[2] else 1) for s in segments)
    ranges = b"".join(struct.pack(">H", 0) for _ in segments)

    body = struct.pack(">HHHH", seg_count * 2, 2 * seg_count, 0, 0)
    sub = struct.pack(">HHH", 4, 16 + 8 * seg_count, 0) + body + ends + b"\0\0" + starts + deltas + ranges
    header = struct.pack(">HH", 0, 1) + struct.pack(">HHI", 3, 1, 12)
    return header + sub


def build():
    glyf = b""
    loca = []
    for _, _, box in GLYPHS:
        loca.append(len(glyf))
        glyf += simple_glyph(box)
    loca.append(len(glyf))

    tables = {
        "head": struct.pack(">IIIIHHQQhhhhHHhhh",
                            0x00010000, 0x00010000, 0, 0x5F0F3CF5, 3, UNITS, 0, 0,
                            0, 0, 600, 700, 0, 8, 2, 0, 0),
        "hhea": struct.pack(">IhhhHhhhhhhhHHHHh",
                            0x00010000, 800, -200, 0, 600, 0, 0, 600, 1, 0, 0, 0,
                            0, 0, 0, 0, len(GLYPHS)),
        "maxp": struct.pack(">IH", 0x00010000, len(GLYPHS)) + b"\0" * 26,
        "hmtx": b"".join(struct.pack(">Hh", g[1], 0) for g in GLYPHS),
        "cmap": cmap_format4(),
        "loca": b"".join(struct.pack(">H", o // 2) for o in loca),
        "glyf": glyf,
        "name": struct.pack(">HHH", 0, 0, 6),
        "post": struct.pack(">IihhIIIIII", 0x00030000, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    }

    order = sorted(tables)
    count = len(order)
    offset = 12 + 16 * count
    directory = b""
    body = b""
    for tag in order:
        data = tables[tag]
        directory += struct.pack(">4sIII", tag.encode(), 0, offset + len(body), len(data))
        body += data + b"\0" * ((4 - len(data) % 4) % 4)

    search_range = 16
    while search_range * 2 <= count * 16:
        search_range *= 2
    header = struct.pack(">IHHHH", 0x00010000, count, search_range, 0, count * 16 - search_range)
    return header + directory + body


def main():
    target = sys.argv[1]
    font = build()
    b64 = base64.b64encode(font).decode()
    parts = [b64[i:i + 200] for i in range(0, len(b64), 200)]

    with open(target, "w") as f:
        f.write("CLASS zcl_pdf_test_font DEFINITION PUBLIC FINAL CREATE PRIVATE.\n")
        f.write("* Generated by tools/gen_test_font.py - do not edit by hand\n")
        f.write("  PUBLIC SECTION.\n")
        f.write('    "! Minimal TrueType font, glyph 1 is A with advance 600, glyph 2 is\n')
        f.write('    "! L with stroke (U+0141) with advance 500, 1000 units per em\n')
        f.write("    CLASS-METHODS ttf\n      RETURNING VALUE(rv_data) TYPE xstring.\n")
        f.write("ENDCLASS.\n\n")
        f.write("CLASS zcl_pdf_test_font IMPLEMENTATION.\n\n")
        f.write("  METHOD ttf.\n")
        f.write("    DATA lv_base64 TYPE string.\n")
        for idx, part in enumerate(parts):
            op = "lv_base64 =" if idx == 0 else "lv_base64 = lv_base64 &&"
            f.write("    %s '%s'.\n" % (op, part))
        f.write("    rv_data = cl_http_utility=>decode_x_base64( lv_base64 ).\n")
        f.write("  ENDMETHOD.\n\nENDCLASS.\n")

    print("written %s (font %d bytes)" % (target, len(font)))


if __name__ == "__main__":
    main()
