#!/usr/bin/env python3
"""Build a minimal but structurally valid sRGB ICC v2 profile.

PDF/A needs an OutputIntent with an ICC profile. In a real system the profile
comes from the customer, from SMW0 or a table. This generator only exists so
that the tests and the demo have one, it is not a colour managed profile.
"""
import struct
import sys
import base64


def s15(value):
    return struct.pack(">i", int(round(value * 65536)))


def xyz_tag(x, y, z):
    return b"XYZ " + b"\0" * 4 + s15(x) + s15(y) + s15(z)


def curve_tag(gamma=2.2):
    return b"curv" + b"\0" * 4 + struct.pack(">I", 1) + struct.pack(">H", int(round(gamma * 256)))


def desc_tag(text):
    raw = text.encode("ascii") + b"\0"
    body = b"desc" + b"\0" * 4 + struct.pack(">I", len(raw)) + raw
    body += struct.pack(">I", 0) + struct.pack(">I", 0)          # unicode
    body += struct.pack(">H", 0) + struct.pack(">B", 0) + b"\0" * 67
    return body


def text_tag(text):
    return b"text" + b"\0" * 4 + text.encode("ascii") + b"\0"


def build():
    tags = [
        (b"desc", desc_tag("sRGB IEC61966-2.1")),
        (b"cprt", text_tag("Public Domain")),
        (b"wtpt", xyz_tag(0.9642, 1.0, 0.8249)),
        (b"rXYZ", xyz_tag(0.4360, 0.2225, 0.0139)),
        (b"gXYZ", xyz_tag(0.3851, 0.7169, 0.0971)),
        (b"bXYZ", xyz_tag(0.1431, 0.0606, 0.7139)),
        (b"rTRC", curve_tag()),
        (b"gTRC", curve_tag()),
        (b"bTRC", curve_tag()),
    ]

    table_size = 4 + 12 * len(tags)
    offset = 128 + table_size
    table = struct.pack(">I", len(tags))
    body = b""
    for sig, data in tags:
        table += sig + struct.pack(">II", offset + len(body), len(data))
        padded = data + b"\0" * ((4 - len(data) % 4) % 4)
        body += padded

    size = 128 + table_size + len(body)
    header = struct.pack(">I", size)
    header += b"none"                                  # preferred CMM
    header += struct.pack(">I", 0x02100000)            # version 2.1
    header += b"mntr" + b"RGB " + b"XYZ "              # class, data, PCS
    header += struct.pack(">HHHHHH", 2026, 1, 1, 0, 0, 0)
    header += b"acsp" + b"\0" * 4                      # signature, platform
    header += struct.pack(">I", 0)                     # flags
    header += b"\0" * 4 + b"\0" * 4                    # manufacturer, model
    header += b"\0" * 8                                # attributes
    header += struct.pack(">I", 0)                     # rendering intent, perceptual
    header += s15(0.9642) + s15(1.0) + s15(0.8249)     # illuminant D50
    header += b"\0" * 4                                # creator
    header += b"\0" * 16                               # profile id
    header += b"\0" * 28                               # reserved
    assert len(header) == 128, len(header)

    return header + table + body


def main():
    target = sys.argv[1]
    icc = build()
    b64 = base64.b64encode(icc).decode()
    parts = [b64[i:i + 200] for i in range(0, len(b64), 200)]

    with open(target, "w") as f:
        f.write("CLASS zcl_pdf_test_icc DEFINITION PUBLIC FINAL CREATE PRIVATE.\n")
        f.write("* Generated by tools/gen_icc.py - do not edit by hand\n")
        f.write("  PUBLIC SECTION.\n")
        f.write('    "! Minimal sRGB ICC profile for the PDF/A output intent\n')
        f.write("    CLASS-METHODS srgb\n      RETURNING VALUE(rv_data) TYPE xstring.\n")
        f.write("ENDCLASS.\n\n")
        f.write("CLASS zcl_pdf_test_icc IMPLEMENTATION.\n\n  METHOD srgb.\n")
        f.write("    DATA lv_base64 TYPE string.\n")
        for idx, part in enumerate(parts):
            op = "lv_base64 =" if idx == 0 else "lv_base64 = lv_base64 &&"
            f.write("    %s '%s'.\n" % (op, part))
        f.write("    rv_data = cl_http_utility=>decode_x_base64( lv_base64 ).\n")
        f.write("  ENDMETHOD.\n\nENDCLASS.\n")

    print("written %s (icc %d bytes)" % (target, len(icc)))


if __name__ == "__main__":
    main()
