#!/usr/bin/env python3
"""Create small deterministic test images and emit them as ABAP base64 constants."""
import base64
import io
import sys
import zlib
import struct


def png_rgb(width, height):
    raw = bytearray()
    for y in range(height):
        raw.append(0)
        for x in range(width):
            raw += bytes([255 - (x * 255 // max(width - 1, 1)),
                          (y * 255 // max(height - 1, 1)),
                          90])
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b""))


def jpeg_rgb(width, height):
    import fitz
    pix = fitz.Pixmap(fitz.csRGB, fitz.IRect(0, 0, width, height))
    for y in range(height):
        for x in range(width):
            pix.set_pixel(x, y, (20, 60 + (x * 150 // width), 140))
    return pix.tobytes("jpg", jpg_quality=80)


def abap_literal(name, data, out):
    b64 = base64.b64encode(data).decode()
    parts = [b64[i:i + 200] for i in range(0, len(b64), 200)]
    out.write("  METHOD %s.\n" % name)
    for idx, part in enumerate(parts):
        op = "rv_base64 =" if idx == 0 else "rv_base64 = rv_base64 &&"
        out.write("    %s '%s'.\n" % (op, part))
    out.write("  ENDMETHOD.\n")


def main():
    target = sys.argv[1]
    png = png_rgb(48, 32)
    jpg = jpeg_rgb(64, 48)

    body = io.StringIO()
    abap_literal("png", png, body)
    body.write("\n")
    abap_literal("jpeg", jpg, body)

    with open(target, "w") as f:
        f.write("CLASS zcl_pdf_test_images DEFINITION PUBLIC FINAL CREATE PRIVATE.\n")
        f.write("* Generated by tools/gen_test_images.py - do not edit by hand\n")
        f.write("  PUBLIC SECTION.\n")
        f.write('    "! 48x32 RGB PNG, base64\n')
        f.write("    CLASS-METHODS png\n      RETURNING VALUE(rv_base64) TYPE string.\n\n")
        f.write('    "! 64x48 RGB JPEG, base64\n')
        f.write("    CLASS-METHODS jpeg\n      RETURNING VALUE(rv_base64) TYPE string.\n")
        f.write("ENDCLASS.\n\n")
        f.write("CLASS zcl_pdf_test_images IMPLEMENTATION.\n\n")
        f.write(body.getvalue())
        f.write("\nENDCLASS.\n")
    print("written %s (png %d bytes, jpeg %d bytes)" % (target, len(png), len(jpg)))


if __name__ == "__main__":
    main()
