#!/usr/bin/env python3
"""Generate the ABAP Base-14 font metrics class from MuPDF's built-in AFM data.

Widths are emitted for WinAnsi codes 32..255 as 3-digit groups in 1/1000 em,
1000 is clamped to 999 (0.1% error, invisible at any practical font size).
"""
import sys

import fitz

FONTS = [
    ("Helvetica", "helv"),
    ("Helvetica-Bold", "hebo"),
    ("Helvetica-Oblique", "heit"),
    ("Helvetica-BoldOblique", "hebi"),
    ("Times-Roman", "tiro"),
    ("Times-Bold", "tibo"),
    ("Times-Italic", "tiit"),
    ("Times-BoldItalic", "tibi"),
    ("Courier", "cour"),
    ("Courier-Bold", "cobo"),
    ("Courier-Oblique", "coit"),
    ("Courier-BoldOblique", "cobi"),
]

LOW = 32
HIGH = 255
CHUNK = 240


def widths(alias):
    font = fitz.Font(alias)
    out = []
    for code in range(LOW, HIGH + 1):
        char = bytes([code]).decode("cp1252", errors="replace")
        w = int(round(font.text_length(char, fontsize=1000)))
        out.append(min(w, 999))
    return "".join("%03d" % w for w in out)


def main():
    target = sys.argv[1]
    lines = []
    a = lines.append

    a("CLASS zcl_open_abap_pdf_metrics DEFINITION PUBLIC FINAL CREATE PRIVATE.")
    a("* Generated by tools/gen_font_metrics.py - do not edit by hand")
    a("  PUBLIC SECTION.")
    a("    CONSTANTS c_first_code TYPE i VALUE %d." % LOW)
    a("    CONSTANTS c_last_code TYPE i VALUE %d." % HIGH)
    a("")
    a("    CONSTANTS c_fonts TYPE string")
    a("      VALUE ',%s,'." % ",".join(n for n, _ in FONTS))
    a("")
    a('    "! Glyph widths in 1/1000 em for WinAnsi codes 32..255, 3 digits each')
    a('    "! @parameter iv_font | Base-14 font name, e.g. Helvetica-Bold')
    a("    CLASS-METHODS widths")
    a("      IMPORTING iv_font          TYPE string")
    a("      RETURNING VALUE(rv_widths) TYPE string.")
    a("")
    a('    "! True for the Base-14 fonts with metrics in this class')
    a("    CLASS-METHODS is_supported")
    a("      IMPORTING iv_font       TYPE string")
    a("      RETURNING VALUE(rv_yes) TYPE abap_bool.")
    a("ENDCLASS.")
    a("")
    a("CLASS zcl_open_abap_pdf_metrics IMPLEMENTATION.")
    a("")
    a("  METHOD widths.")
    a("    CASE iv_font.")
    for name, alias in FONTS:
        data = widths(alias)
        parts = [data[i:i + CHUNK] for i in range(0, len(data), CHUNK)]
        a("      WHEN '%s'." % name)
        for idx, part in enumerate(parts):
            op = "rv_widths =" if idx == 0 else "rv_widths = rv_widths &&"
            a("        %s '%s'." % (op, part))
    a("      WHEN OTHERS.")
    a("        rv_widths = widths( 'Helvetica' ).")
    a("    ENDCASE.")
    a("  ENDMETHOD.")
    a("")
    a("  METHOD is_supported.")
    a("    rv_yes = xsdbool( c_fonts CS |,{ iv_font },| ).")
    a("  ENDMETHOD.")
    a("")
    a("ENDCLASS.")

    with open(target, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("written %s (%d lines)" % (target, len(lines)))


if __name__ == "__main__":
    main()
